name: wellness_diary
description: "A new Flutter project for mindful wellness tracking."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.31.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.1
  intl: ^0.18.1
  flutter_local_notifications: ^15.1.1
  provider: ^6.1.1

dependency_overrides:
  firebase_core_web: ^2.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Optional: Add assets here if you're using icons, images, or fonts
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Optional: Fonts section if you want custom typography
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: fonts/OpenSans-Regular.ttf
  #       - asset: fonts/OpenSans-Bold.ttf
  #         weight: 700
