import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    runApp(const WellnessDiaryApp());
  } catch (e) {
    print('Firebase initialization error: $e');
  }
}

class WellnessDiaryApp extends StatelessWidget {
  const WellnessDiaryApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Add your state management providers here
      ],
      child: MaterialApp(
        title: 'Wellness Diary',
        theme: ThemeData(
          primarySwatch: Colors.green,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: const HomePage(),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Welcome to Wellness Diary')),
      body: const Center(
        child: Text(
          'Firebase is initialized!',
          style: TextStyle(fontSize: 18),
        ),
      ),
    );
  }
}
